apiVersion: apps/v1
kind: Deployment
metadata:
  name:  comments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments # pod label
  template:
    metadata:
      labels:
        app: comments # NAME FOR OUR POD
    spec:
      # configuration for pod
      containers:
      - name: comments
        image: 199619961234/comments:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: comments-cluster-ip-service
spec:
  selector:
    app: comments # pod label
  ports:
  - name: comments # pod label
    protocol: TCP
    port: 4001
    targetPort:  4001 # port used in the application (container)